modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/hungbbdzz/vein-farming/issues"
displayURL="https://github.com/hungbbdzz/vein-farming"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"
logoFile="logo.png"

[[dependencies.vein_farming]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vein_farming]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.vein_farming]]
modId="liteminer"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"

[[dependencies.vein_farming]]
modId="ftbultimine"
type="optional"
versionRange="*"
ordering="AFTER"
side="BOTH"
